### ISSUE TITLE
Just want to point a few things out for new users like myself

### ISSUE THREAD

**Issue by OliverDayunLiu** [ofsoundof/3D_Appearance_SR#1]
1. Once you download the texture data, make sure the folder's name is Texture_map and not texture_map. Texture_map folder shall contain 4 subfolders: Collection, ETH3D, MiddleBury and SyB3R

2. In code/options.py, change the '--dir' and '--dir_data' arguments. Example:

Previous: parser.add_argument('--dir', type=str, default='/scratch_net/ofsoundof/yawli/logs_3d/',
                    help='log directory')
New: parser.add_argument('--dir', type=str, default='/home/oliver/Desktop/3DASR/logs_3d/',
                    help='log directory')

Previous: parser.add_argument('--dir_data', type=str, default='/scratch_net/ofsoundof/yawli/Datasets/', help='dataset directory')
New: parser.add_argument('--dir_data', type=str, default='/home/oliver/Desktop/3DASR/Datasets/',
                    help='dataset directory')

The content of Datasets folder look like this:
Datasets
    -Texture_map
           -Collection
           -ETH3D
           -MiddleBury
           -SyB3R

3. Add --ext sep_reset to arguments if you get an error saying .npy files don't exist
4. CUDA_VISIBLE_DEVICES=xx didn't work for me. CUDA_VISIBLE_DEVICES=0 worked.
5. If you run NHR instead of NLR: in trainer_finetune.py's make_optimizer function, change

finetune_id = list(map(id, model.model.body_ft.parameters())) \
                      + list(map(id, model.model.tail_ft.parameters()))

         to:

finetune_id = list(map(id, model.model.body_ft.parameters())) \
                      + list(map(id, model.model.tail_ft1.parameters()))   \
         + list(map(id, model.model.tail_ft2.parameters()))

Hope these helps.

**Comment by ofsoundof** [comment]
>     1. Once you download the texture data, make sure the folder's name is Texture_map and not texture_map. Texture_map folder shall contain 4 subfolders: Collection, ETH3D, MiddleBury and SyB3R
> 
>     2. In code/options.py, change the '--dir' and '--dir_data' arguments. Example:
> 
> 
> Previous: parser.add_argument('--dir', type=str, default='/scratch_net/ofsoundof/yawli/logs_3d/',
> help='log directory')
> New: parser.add_argument('--dir', type=str, default='/home/oliver/Desktop/3DASR/logs_3d/',
> help='log directory')
> 
> Previous: parser.add_argument('--dir_data', type=str, default='/scratch_net/ofsoundof/yawli/Datasets/', help='dataset directory')
> New: parser.add_argument('--dir_data', type=str, default='/home/oliver/Desktop/3DASR/Datasets/',
> help='dataset directory')
> 
> The content of Datasets folder look like this:
> Datasets
> -Texture_map
> -Collection
> -ETH3D
> -MiddleBury
> -SyB3R
> 
>     1. Add --ext sep_reset to arguments if you get an error saying .npy files don't exist
> 
>     2. CUDA_VISIBLE_DEVICES=xx didn't work for me. CUDA_VISIBLE_DEVICES=0 worked.
> 
>     3. If you run NHR instead of NLR: in trainer_finetune.py's make_optimizer function, change
> 
> 
> finetune_id = list(map(id, model.model.body_ft.parameters()))
> + list(map(id, model.model.tail_ft.parameters()))
> 
> ```
>      to:
> ```
> 
> finetune_id = list(map(id, model.model.body_ft.parameters()))
> + list(map(id, model.model.tail_ft1.parameters()))
> + list(map(id, model.model.tail_ft2.parameters()))
> 
> Hope these helps.
Thank your very much for the comments!

**Comment by ofsoundof** [comment]
>     1. Once you download the texture data, make sure the folder's name is Texture_map and not texture_map. Texture_map folder shall contain 4 subfolders: Collection, ETH3D, MiddleBury and SyB3R
> 
>     2. In code/options.py, change the '--dir' and '--dir_data' arguments. Example:
> 
> 
> Previous: parser.add_argument('--dir', type=str, default='/scratch_net/ofsoundof/yawli/logs_3d/',
> help='log directory')
> New: parser.add_argument('--dir', type=str, default='/home/oliver/Desktop/3DASR/logs_3d/',
> help='log directory')
> 
> Previous: parser.add_argument('--dir_data', type=str, default='/scratch_net/ofsoundof/yawli/Datasets/', help='dataset directory')
> New: parser.add_argument('--dir_data', type=str, default='/home/oliver/Desktop/3DASR/Datasets/',
> help='dataset directory')
> 
> The content of Datasets folder look like this:
> Datasets
> -Texture_map
> -Collection
> -ETH3D
> -MiddleBury
> -SyB3R
> 
>     1. Add --ext sep_reset to arguments if you get an error saying .npy files don't exist
> 
>     2. CUDA_VISIBLE_DEVICES=xx didn't work for me. CUDA_VISIBLE_DEVICES=0 worked.
> 
>     3. If you run NHR instead of NLR: in trainer_finetune.py's make_optimizer function, change
> 
> 
> finetune_id = list(map(id, model.model.body_ft.parameters()))
> + list(map(id, model.model.tail_ft.parameters()))
> 
> ```
>      to:
> ```
> 
> finetune_id = list(map(id, model.model.body_ft.parameters()))
> + list(map(id, model.model.tail_ft1.parameters()))
> + list(map(id, model.model.tail_ft2.parameters()))
> 
> Hope these helps.

Thank you very much for your comments!

**Comment by ofsoundof** [comment]
>     1. Once you download the texture data, make sure the folder's name is Texture_map and not texture_map. Texture_map folder shall contain 4 subfolders: Collection, ETH3D, MiddleBury and SyB3R
> 
>     2. In code/options.py, change the '--dir' and '--dir_data' arguments. Example:
> 
> 
> Previous: parser.add_argument('--dir', type=str, default='/scratch_net/ofsoundof/yawli/logs_3d/',
> help='log directory')
> New: parser.add_argument('--dir', type=str, default='/home/oliver/Desktop/3DASR/logs_3d/',
> help='log directory')
> 
> Previous: parser.add_argument('--dir_data', type=str, default='/scratch_net/ofsoundof/yawli/Datasets/', help='dataset directory')
> New: parser.add_argument('--dir_data', type=str, default='/home/oliver/Desktop/3DASR/Datasets/',
> help='dataset directory')
> 
> The content of Datasets folder look like this:
> Datasets
> -Texture_map
> -Collection
> -ETH3D
> -MiddleBury
> -SyB3R
> 
>     1. Add --ext sep_reset to arguments if you get an error saying .npy files don't exist
> 
>     2. CUDA_VISIBLE_DEVICES=xx didn't work for me. CUDA_VISIBLE_DEVICES=0 worked.
> 
>     3. If you run NHR instead of NLR: in trainer_finetune.py's make_optimizer function, change
> 
> 
> finetune_id = list(map(id, model.model.body_ft.parameters()))
> + list(map(id, model.model.tail_ft.parameters()))
> 
> ```
>      to:
> ```
> 
> finetune_id = list(map(id, model.model.body_ft.parameters()))
> + list(map(id, model.model.tail_ft1.parameters()))
> + list(map(id, model.model.tail_ft2.parameters()))
> 
> Hope these helps.


Thank you very much for your comments to clarify the ambiguity.
1. The directory of the Dataset folder is important for the system to recognize it. 
2. '--dir' and '--dir_data' should be changed according to your local directory.
3. This is right. We use .npy file instead of .png. So by setting '--ext_sep_reset', the .png images are converted to .npy.
4. If you only have 1 GPU, set CUDA_VISIBLE_DEVICES=0 directly.

**Comment by shentucc** [comment]
could you tell me  which  datasets  put in the“--dir', type=str, default='/scratch_net/ofsoundof/yawli/logs_3d/”？

**Comment by ChowKwanYinDavid** [comment]
I got "freeze_support()' problem, after I ran this code. Anybody has a solution?
I have checked this problem in github([https://github.com/pytorch/pytorch/issues/5858](url)), but I don't know where I should put  the def run() in which python code. Can anybody help me?
OS: win10 ,python 3.6 ,pytorch 1.0
  File "<string>", line 1, in <module>
  File "D:\Anaconda\envs\py3.6_2\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\Anaconda\envs\py3.6_2\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "D:\Anaconda\envs\py3.6_2\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\Anaconda\envs\py3.6_2\lib\multiprocessing\spawn.py", line 276, in _fixup_main_from_path
    run_name="__mp_main__")
  File "D:\Anaconda\envs\py3.6_2\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "D:\Anaconda\envs\py3.6_2\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "D:\Anaconda\envs\py3.6_2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\NTNU\Vis_Lab\SR model\3D_Appearance_SR-master\code\main.py", line 19, in <module>
    while not t.terminate():
  File "D:\NTNU\Vis_Lab\SR model\3D_Appearance_SR-master\code\trainer.py", line 141, in terminate
    self.test()
  File "D:\NTNU\Vis_Lab\SR model\3D_Appearance_SR-master\code\trainer_finetune.py", line 97, in test
    for idx_img, (lr, nl, mk, hr, filename, _) in enumerate(tqdm_test):
  File "D:\Anaconda\envs\py3.6_2\lib\site-packages\tqdm\_tqdm.py", line 897, in __iter__
    for obj in iterable:
  File "D:\NTNU\Vis_Lab\SR model\3D_Appearance_SR-master\code\dataloader_new.py", line 171, in __iter__
    return _MSDataLoaderIter(self)
  File "D:\NTNU\Vis_Lab\SR model\3D_Appearance_SR-master\code\dataloader_new.py", line 127, in __init__
    w.start()
  File "D:\Anaconda\envs\py3.6_2\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\Anaconda\envs\py3.6_2\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Anaconda\envs\py3.6_2\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\Anaconda\envs\py3.6_2\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "D:\Anaconda\envs\py3.6_2\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "D:\Anaconda\envs\py3.6_2\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "../main.py", line 19, in <module>
    while not t.terminate():
  File "D:\NTNU\Vis_Lab\SR model\3D_Appearance_SR-master\code\trainer.py", line 141, in terminate
    self.test()
  File "D:\NTNU\Vis_Lab\SR model\3D_Appearance_SR-master\code\trainer_finetune.py", line 97, in test
    for idx_img, (lr, nl, mk, hr, filename, _) in enumerate(tqdm_test):
  File "D:\Anaconda\envs\py3.6_2\lib\site-packages\tqdm\_tqdm.py", line 897, in __iter__
    for obj in iterable:
  File "D:\Anaconda\envs\py3.6_2\lib\site-packages\torch\utils\data\dataloader.py", line 631, in __next__
    idx, batch = self._get_batch()
  File "D:\Anaconda\envs\py3.6_2\lib\site-packages\torch\utils\data\dataloader.py", line 601, in _get_batch
    return self.data_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "D:\Anaconda\envs\py3.6_2\lib\queue.py", line 173, in get
    self.not_empty.wait(remaining)
  File "D:\Anaconda\envs\py3.6_2\lib\threading.py", line 299, in wait
    gotit = waiter.acquire(True, timeout)
