### ISSUE TITLE
Testing with a different dataset of Texture map

### ISSUE THREAD

**Issue by marcopesavento** [ofsoundof/3D_Appearance_SR#2]
Hi, I was trying to use the network to super resolve a different dataset of Texture maps with the relative masks and normal maps. The dimensions of the new Texture maps are however different from the original ones. 
To test the network, I used the given pretrained models but I obtained the following error :

" THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1544174967633/work/aten/src/THC/THCGeneral.cpp line=405 error=11 : invalid argument
  0%|                                                    | 0/12 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "../main.py", line 19, in <module>
    while not t.terminate():
  File "/vol/research/volcap/MP/3D_Appearance_SR-master-train/code/trainer.py", line 141, in terminate
    self.test()
  File "/vol/research/volcap/MP/3D_Appearance_SR-master-train/code/trainer_finetune.py", line 110, in test
    sr = self.model(idx_scale, lr, nl, mk)
  File "/vol/research/volcap/MP/anaconda3/envs/textsr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/vol/research/volcap/MP/3D_Appearance_SR-master-train/code/model/__init__.py", line 56, in forward
    return self.forward_chop(x)
  File "/vol/research/volcap/MP/3D_Appearance_SR-master-train/code/model/__init__.py", line 167, in forward_chop
    for patch in zip(lr_list, nl_list)
  File "/vol/research/volcap/MP/3D_Appearance_SR-master-train/code/model/__init__.py", line 167, in <listcomp>
    for patch in zip(lr_list, nl_list)
  File "/vol/research/volcap/MP/3D_Appearance_SR-master-train/code/model/__init__.py", line 159, in forward_chop
    sr_batch = self.model((lr_batch, nl_batch))
  File "/vol/research/volcap/MP/anaconda3/envs/textsr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/vol/research/volcap/MP/3D_Appearance_SR-master-train/code/model/finetune.py", line 252, in forward
    x = self.tail_ft2(x)
  File "/vol/research/volcap/MP/anaconda3/envs/textsr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/vol/research/volcap/MP/anaconda3/envs/textsr/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/vol/research/volcap/MP/anaconda3/envs/textsr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/vol/research/volcap/MP/anaconda3/envs/textsr/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/vol/research/volcap/MP/anaconda3/envs/textsr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/vol/research/volcap/MP/anaconda3/envs/textsr/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [260, 260, 3, 3], expected input[1, 259, 540, 540] to have 260 channels, but got 259 channels instead "

It seems to be an error related to the pretrained model used for inference. Therefore, I would like to ask if there are specific options to set to make the framework working with different datasets without changing the network model or if the pretrained models can be used exclusively with the given dataset.
In the case that the problem is not related to the input dataset, then what could it be?

**Comment by marcopesavento** [comment]
I solved the issue. The problem was in the normal maps that didn't have the 4-th channel.
